# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
- test
- deploy
sast:
  stage: test

deploy_job:
  only:
    - main
  stage: deploy
  script:
    - sudo composer install
    - sudo npm install
    - sudo npm run prod
    - sudo rm -rf ./node_modules
    - sudo cp -r . /var/www/html/
    - sudo chmod 777 -R /var/www/html/storage/logs
  tags:
    - prod

include:
- template: Security/SAST.gitlab-ci.yml
